simulate: True

Rbin: R
STAR: STAR
featureCounts: featureCounts
bedtools: bedtools
bedGraphToBigWig: bedGraphToBigWig
faSize: faSize
nthreads: 2
max_mem_mb: 20000

## mind to update this to the full or relative path the git repo is cloned to
rock_method_path: "."

working_dir: work

gtf: genome.gtf
genome: genome.fa

# i.e. cDNA read length minus 1
sjdbOverhang: 149

## run mode, one of these (please see the README / docs):
##   'tso off- and ontarget unique'
##   'tso ontarget_multi'
##   'all'
run_mode: 'tso off- and ontarget unique'

## GTF `source` field identifying on-target rock- or roi- features
capture_gtf_column_2_pattern : 'captured'
featurecounts_t: 'exon' ## feature counting unit for featurecounts
featurecounts_g: 'gene_id' ## feature grouping unit for featurecounts

## these are not used by the simulations, but must be updated with
##   the experimental design for sequenced data
samples:
  - name: simul
    uses:
      cb_umi_fq: empty_r1.fq.gz
      cdna_fq: empty_r2.fq.gz
      whitelist: 384x3  ## so full CB allowedlist
